# Generated by Django 2.2 on 2020-05-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
    ]
