# Generated by Django 2.2 on 2020-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bein_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
